### PR TITLE
refine how we post agent data to influxdb for state timeline, status …

### PR DESCRIPTION
**Pull request by hum4n0id**
…history views

### CODE REVIEW

**Review by plars — CHANGES_REQUESTED** [review]
Can you give a little more detail here on what's changing and why? Were you able to preserve pushing status updates with result codes in only some cases without injecting short  phases into the timeline?

**Comment by hum4n0id** [comment]
Sure!

Calling client.post_influx() in set_agent_state() to capture a complete timeline of when an agent changes state/phase. In order to be able to call client.post_influx method in set_agent_state, we need to drop 'duration' and 'result.' 'Result’ does not work in the state timeline context, and ‘duration’ is not necessary and can be derived from the database measurements themselves (via time). This allows a clear and complete picture of agent activity in Grafana.

We will continue to call post_influx() in the original location (process_jobs()), to enable capturing the result of test phases where applicable. This will be called with phase and result as we are using this call to fill in the secondary 'status history' view in Grafana - displaying a horizontal timeline of the history of each test/job phase.

In client.post_influx() we have defined result as a keyword/named argument and will post result as an additional field to SELECT from in our query when populating the 'status history' panel. We are also populating "data['time']" with time.time_ns() for cleanliness, as Influx requires measurements in ns. This means we do not need to cast a time.time() call to int and can drop 'time_precision' parameter in influx_client.write_points(), which converts measurements to ns.

**Comment by plars** [comment]
I think what I'm confused about here is that we're still using the same measurement for both:
```
"measurement": "phase result",
```
So my first question is: can you definitely use grafana to *only* consider the phase duration data for creating the state timeline without it being polluted by result data inside the same measurement? This seemed to be a problem when you showed me the graphs last time, which is why we said it might be necessary to create a separate measurement for the phase results.
Can you show how you've confirmed that the result data is not polluting the graph?

Next, it looks like we've gone from having a tag for the phase and the result to having a field for the phase, and possibly a field for the result as well.  We discussed tags vs fields before. My understanding is that influxdb indexes the tags, but not the fields. So using a field name is really appropriate for things where you might have lots of different values. Using a tag is better when you have a limited set of possible values and you'd like to query them very fast.
Why did we change to using a field for the phase at least? This should not have many possible values.

**Review by plars — APPROVED** [review]
Adrian and I reviewed this over google meet and he was able to answer my remaining questions. There's no negative effect to landing this, so lets merge it since I can see that it definitely helps us get at least one of the views we're looking for.

**Pull request merged**
